### ISSUE TITLE
App sample - Interact mode to send commands

### ISSUE THREAD

**Issue by gabrielbmoro** [CodandoTV/jujubaSVG#6]
Currently the app sample is very poor, we are just showing one command. I was thinking we could create a selector to select a command to be applied to the SVG map. In this way, the user could try all commands : )

**Comment by arthurhenz** [comment]
To brainstorm it, I come with three solutions:

1. Use a selector to select a command to be applied to the SVG map (I don't think I understood 100% the UI, were yout thinking like a dropdown somewhere?)
2. Use [airbnb's Showkase](https://github.com/airbnb/Showkase) in order to have a different scenario for each command (the best imo)
3. Place a Material3 fixed sheet and turbinate the existing scenario

For me these 3 options are effective so what would you pick?

**Comment by arthurhenz** [comment]
For suure! Cooking something, on the way :)
